### PR TITLE
Feature/return raw response

### PR DESCRIPTION
**Pull request by madwings**

### CODE REVIEW

**Comment by samoritano** [comment]
Hi @madwings .

It seems @zoonman cannot maintain this repo anymore. I offered myself to help him a few months ago and he wasn't able to spend any time with it, and also suggested people to use my fork.

It would be nice to unify our efforts in one single repo, since we both are keep the code updated. I already forked and pushed the repo into a [new vendor](https://packagist.org/packages/samoritano/linkedin-api-php-client-v2) for using it with composer.

So please, feel free to do any PR into my fork, so we can keep the code updated for the community.

Thank you.

**Comment by madwings** [comment]
Hey @samoritano 
I have looked into your repo. I have actually reused some of the improvements.
But also I have seen some bad practices which if continued will make that library bloated and buggy.
1. Bump of Guzzle to v7 - https://github.com/samoritano/linkedin-api-php-client/commit/8574cd9185a8ca6a376eb4b3e44cbe1e6e53aafe. Guzzle 6 is still maintained and used in lots of repos in the PHP world. With that change you introduce lots of compatibility issues. I cannot use it with that change. If it is not strictly required the better approach is to make it like this: guzzlehttp/guzzle": "^6.3 || ^7.0". Also introducing such breaking change on a patch version is a bad practice.
2. Direct push to master without a pull request for an important change - https://github.com/samoritano/linkedin-api-php-client/commit/67c95b7e2e0ca1aeb409864eb8153a860d694e46. Not to mention that this change is wrong in so many ways. It is bad software design. Basically you break one responsibility rule. Magic numbers inside the code, which does not make sense. Change made just to be used from one other function. It opens a way to use Guzzle directly through the library. That library is a wrapper around the LinkedIn API, not a wrapper around Guzzle. And so on. So if you want to make your repo the mainstream version you need to apply good practices and rules.
3. Seeing this I cannot rely on this repo to be stable and reliable. For now I will continue changes in a separate repo. Here it is - https://github.com/postplanner/linkedin-api-php-client. Feel free to use anything you find usable and worth while in you repo.

**Comment by samoritano** [comment]
Hi @madwings.

First of all, I want to thank you for taking some time to review our code. 

We have developed a marketing tool clients that heavily relays in Linkedin api, so we just forked the original repo in order to solve some Linkedin V2 api issues,  because we must keep our tool alive, since the repo was kind of abandoned.

That's why sometimes we need to solve some issues as fast as we can, and we mostly don't think about this repo as an OSS library, but as an internal library, so we have pushed a few commits that may have not follow the best practices.

Anyway, after saying that, I must recognise that you're absolutely right about your points, and we have no excuse for not applying good practices, if we want to keep our repo as an OSS.

I'm gonna review the code with the main developer of my team ( I don't usually write code, I'm a DevOps guy), so we can fix  this bad practices and keep the repo as clean as we can.

I'll let you know about this refactor, if you still consider that we can join efforts in order to keep the library updated.

**Comment by madwings** [comment]
Well, we use LinkedIn API. So we need that library. It was a good foundation as a start. So I have to update it if we want our product to work smooth.

**Comment by samoritano** [comment]
Ok then.

We'll push the refactor of our repo later this week, and we'll check your commits so we can reuse your changes.

I'll keep you informed.

Thx.

**Comment by samoritano** [comment]
HI @madwings , we made some  changes in our repo, following your recommendations.

Feel free to check them out, so maybe we can collaborate in a common repository from here.

**Comment by madwings** [comment]
Looks better. I will prepare my changes.

**Pull request closed without merging**
