### PR TITLE
Allow to use refresh token method for renewing token

### PR DESCRIPTION
**Pull request by samoritano**
Linkedin has recently added a feature that allows to renew user tokens from a new refresh token parameter.
I've done some minor changes to allow renewing existing tokens with this option.

### CODE REVIEW

**Comment by waqasasif9292** [comment]
@zoonman I'm also waiting for this PR to get merged.

**Comment by samoritano** [comment]
> zoonman I'm also waiting for this PR to get merged.
Hi, @waqasd4int.

I sent @zoonman an email offering help from my team for maintaining this repo, but I didn't got an answer. Now I'm using my [own fork](https://packagist.org/packages/samoritano/linkedin-api-php-client-v2) for production purposes since then.

I thought it was better to keep this library updated, since it has so many installs, but I think I'll keep my fork updated, since there're some changes I'd like to implement (better error management and other features).

**Comment by zoonman** [comment]
Guys, I have no bandwidth to tackle this right now. 
Please use Samoritano’s version for now. 

I check it out later.

**Comment by samoritano** [comment]
> Guys, I have no bandwidth to tackle this right now.
> Please use Samoritano’s version for now.
> 
> I check it out later.

Ok, @zoonman , no problem. I'll try to keep updated my library.

Thank you anyway!

**Comment by waqasasif9292** [comment]
@samoritano Thank you

**Pull request closed without merging**
