### PR TITLE
fixes zoonman//linkedin-api-php-client#51

### PR DESCRIPTION
**Pull request by shaneiseminger**

### CODE REVIEW

**Comment by Jaspur** [comment]
@zoonman can you merge this?

**Comment by samoritano** [comment]
Hi, @Jaspur , this package has been abandoned by his author. Me and my team forked a few months ago, and we are keeping it updated [here](https://github.com/samoritano/linkedin-api-php-client), with a [composer package](https://packagist.org/packages/samoritano/linkedin-api-php-client-v2) already published.

Please, feel free to collaborate in our repo, if you like.

Regards.

**Comment by zoonman** [comment]
Don't have time for this now. Use forks, please.

**Comment by shaneiseminger** [comment]
I'm going ahead and closing this.

1. I opened it against a `master` branch. I will likely need to make more commits there and I don't intend to keep pushing more commits into this PR.
2. Seems that it's not going to get merged anyway.

@zoonman I appreciate the work on this library to date. Since you're not able to continue it--which I totally understand--can I suggest that you choose a well-maintained and active fork and transfer the repo to that person or group? Otherwise, there's a great amount of code fragmentation. People are still finding this library and eventually realizing it doesn't completely work for them, then either having to find one of the 57 forks that does work or making their own fixes. If you hand it off to someone, then that one could be considered the source of truth that's easier to find in searches, and people will resume collaborating on it there.

**Pull request closed without merging**
